### ISSUE TITLE
Solicitud de cambio de criterios para cálculo de Prima

### ISSUE THREAD

**Issue by cmonsalvec** [luis0088/JenkinsTest#2]
Estimados,

De acuerdo a las estadísticas del 2019 hemos comprobado que la siniestralidad de conductores de 65 años de edad o más ha aumentado. Por tal razón el directorio de nuestra empresa ha decidido modificar para este rango de edad el número de puntos que puede perder en su licencia de conducir. El directorio ha aprobado que ese número de puntos pase de 5 a 4.

Por favor realizar los cambios en el sistema para que esta nueva disposición del directorio pueda entrar en funcionamiento.

**Comment by luis0088** [comment]
Hemos reproducido el problema y se ha constatado la necesidad de modificar el software.

**Comment by luis0088** [comment]
Se ha categorizado el problema y se ha añadido el milestone.

**Comment by fervacaleon** [comment]
Se ha realizado el análisis de impacto del incidente: El problema tiene un leve impacto en cuánto a los cambios que se tendrán que hacer en el código, puesto que se trata del único módulo del proyecto. El tiempo que tomará realizar este cambio es de menos de 1 hora y los costos para el mismo son mínimos. 

@cmonsalvec ¿Está de acuerdo con el análisis?

**Comment by cmonsalvec** [comment]
Muchas gracias, estoy de acuerdo con los términos producto del análisis, favor continuar con el cambio requerido.

**Comment by JoseAndresEscobar19** [comment]
Se realizó el cambio requerido en el software sobre la cantidad de puntos permitidos de 5 a 4 para personas mayores o igual a 65 años de edad.

Se adjunta el plan de pruebas y esperamos su confirmación:
[Plan de Pruebas Issue#2.pdf](https://github.com/luis0088/JenkinsTest/files/4094789/Plan.de.Pruebas.Issue.2.pdf)

**Comment by cmonsalvec** [comment]
Muchas gracias por proponer un plan de pruebas. De acuerdo. Favor informarme de los resultados de la ejecución de las pruebas.

**Comment by JoseAndresEscobar19** [comment]
Entendido, se procedió a realizar las pruebas

**Pruebas de integración**
No aplican, el programa cuenta con un solo módulo

Se escribieron las pruebas de acuerdo con el plan aprobado.
Con un total de 18 pruebas, se obtuvo el siguiente resultado:
![Pruebas](https://user-images.githubusercontent.com/25187681/72922757-a16e6780-3d1b-11ea-83f7-b52c2b98d357.JPG)

Se paso con éxito las 18 pruebas planeadas.

Se procede a las pruebas de aceptación

**Comment by cmonsalvec** [comment]
Excelente, muchas gracias.

**Comment by sbrodrig** [comment]
Para las pruebas de aceptación se plantearon 7 escenarios, todos pasaron.
![pruebas de aceptacion](https://user-images.githubusercontent.com/39098573/72957690-8b3fc600-3d72-11ea-9fe3-af843b57efbd.JPG)

@cmonsalvec ¿Está usted de acuerdo con las pruebas de aceptación que se realizaron?

**Comment by cmonsalvec** [comment]
Muchas gracias, si, estoy de acuerdo con las pruebas realizadas

**Comment by sbrodrig** [comment]
Una vez aprobadas las pruebas de aceptación, continuo con la verificación de las etapas completadas:

- Reproducir del problema: **COMPLETADO**

- Categorizar el incidente: **COMPLETADO**

- Asignar el incidente a un miembro del equipo: **COMPLETADO**

- Análisis del impacto: **COMPLETADO**

- Solución del incidente: **COMPLETADO**

- Realizar pruebas de sistema e integración: **COMPLETADO**

- Realizar pruebas de aceptación: **COMPLETADO**

Procedo con el cierre del issue @cmonsalvec
